### ISSUE TITLE
Sign-In Required to Read Documentation

### ISSUE THREAD

**Issue by jeixav** [aws-samples/twinmodules#2]
The [README](https://github.com/aws-samples/twinmodules/blob/16892cbf8367fa611cb8918b28f872e575768f8a/README.md) gives a link to API documentation: https://gitlab.aws.dev/autonomouscomputesateam/twinmodules/-/tree/main/docs/_build/html. This link seems to lead to a sign-in page (Midway Authentication Portal).

Is this intentional? I am unclear on what credentials are requested.

**Comment by awspiv** [comment]
Ah sorry this is an error in the link.  I will update soon, I need to move the doc to readthedocs.

**Comment by awspiv** [comment]
Links are fixed, docs updated.
